spring:
  profiles:
    include: secret
---


server:
  port: 9090
  redirection:
    domain: http://localhost:9090/link

grpc:
  server:
    port: 9091
    address: 0.0.0.0
    api-key: ${GRPC_API_KEY:test-api-key}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000
      leak-detection-threshold: 2000

  jpa:
    open-in-view: false
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    hibernate:
      ddl-auto: ${SPRING_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

constant:
  default-expiration-days: 7
  url:
    max-length: 2048
  hash:
    length: 8
    conflict:
      retry: 3

scheduler:
  expired-url-deletion:
    cron: "0 0 3 * * *"
    batch-size: 500
